/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import BLL.UpdateData;
import BLL.GetData;
import BLL.GetValue;
import java.util.ArrayList;
import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import com.toedter.calendar.JDateChooser;
import java.text.DecimalFormat;

/**
 *
 * @author ASUS
 */
public class Menu extends javax.swing.JFrame {

    private GetData x;
    private UpdateData t;
    private GetValue y;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        x = new GetData();
        y = new GetValue();
        t = new UpdateData();

        initValue();
        setLocationRelativeTo(null);
    }
    private int demSoLanThem = 0;
    private int demSoLanCapNhat = 0;
    private  int demSoLanXoa = 0;
    private JDateChooser dateChooser;

    private void initValue() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tab1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tab2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tab3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tab4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tab5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        tab6 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jp2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_HD = new javax.swing.JTable();
        btn_SuaHD = new javax.swing.JButton();
        btn_themHD = new javax.swing.JButton();
        btn_showHD = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_MAHD = new javax.swing.JTextField();
        txt_HTTT = new javax.swing.JTextField();
        txt_MANV = new javax.swing.JTextField();
        txt_MAKM = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        txt_MAKH = new javax.swing.JTextField();
        btn_Date = new com.toedter.calendar.JDateChooser();
        jp4 = new javax.swing.JPanel();
        btn_showKM = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_KM = new javax.swing.JTable();
        btn_themKM = new javax.swing.JButton();
        txt_makm = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txt_tile = new javax.swing.JTextField();
        txt_tenkm = new javax.swing.JTextField();
        btn_capnhatKM = new javax.swing.JButton();
        btn_xoaKM = new javax.swing.JButton();
        jp3 = new javax.swing.JPanel();
        btn_showKH = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_KH = new javax.swing.JTable();
        btn_ThemKH = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        chooser_KH = new com.toedter.calendar.JDateChooser();
        jLabel24 = new javax.swing.JLabel();
        txt_makh = new javax.swing.JTextField();
        txt_tenkh = new javax.swing.JTextField();
        txt_GT = new javax.swing.JTextField();
        txt_sdt = new javax.swing.JTextField();
        txt_diemtluy = new javax.swing.JTextField();
        btn_suaKH = new javax.swing.JButton();
        btn_xoakh = new javax.swing.JButton();
        jp1 = new javax.swing.JPanel();
        btn_showTD = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_TD = new javax.swing.JTable();
        btn_ThemTD = new javax.swing.JButton();
        txt_mota = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_matd = new javax.swing.JTextField();
        txt_tenmon = new javax.swing.JTextField();
        txt_gia = new javax.swing.JTextField();
        txt_kc = new javax.swing.JTextField();
        txt_TT = new javax.swing.JTextField();
        txt_ml = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btn_CapNhatTD = new javax.swing.JButton();
        btn_xoaTD = new javax.swing.JButton();
        jp5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        table_CTHD = new javax.swing.JTable();
        btn_themcthd = new javax.swing.JButton();
        btn_showCTHD = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txt_sl = new javax.swing.JTextField();
        txt_macthd = new javax.swing.JTextField();
        txt_macthdtd = new javax.swing.JTextField();
        jp6 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(222, 244, 255));

        tab1.setBackground(new java.awt.Color(255, 153, 153));
        tab1.setRequestFocusEnabled(false);
        tab1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Hóa Đơn");

        javax.swing.GroupLayout tab1Layout = new javax.swing.GroupLayout(tab1);
        tab1.setLayout(tab1Layout);
        tab1Layout.setHorizontalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        tab1Layout.setVerticalGroup(
            tab1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        tab2.setBackground(new java.awt.Color(255, 153, 153));
        tab2.setPreferredSize(new java.awt.Dimension(176, 48));
        tab2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab2MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Thực Đơn");
        jLabel2.setPreferredSize(new java.awt.Dimension(176, 48));

        javax.swing.GroupLayout tab2Layout = new javax.swing.GroupLayout(tab2);
        tab2.setLayout(tab2Layout);
        tab2Layout.setHorizontalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        tab2Layout.setVerticalGroup(
            tab2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab3.setBackground(new java.awt.Color(255, 153, 153));
        tab3.setPreferredSize(new java.awt.Dimension(176, 48));
        tab3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab3MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Khách Hàng");

        javax.swing.GroupLayout tab3Layout = new javax.swing.GroupLayout(tab3);
        tab3.setLayout(tab3Layout);
        tab3Layout.setHorizontalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        tab3Layout.setVerticalGroup(
            tab3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab4.setBackground(new java.awt.Color(255, 153, 153));
        tab4.setPreferredSize(new java.awt.Dimension(176, 48));
        tab4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab4MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Khuyến Mãi");

        javax.swing.GroupLayout tab4Layout = new javax.swing.GroupLayout(tab4);
        tab4.setLayout(tab4Layout);
        tab4Layout.setHorizontalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        tab4Layout.setVerticalGroup(
            tab4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 139, 143));
        jLabel5.setText("Coffee");

        tab5.setBackground(new java.awt.Color(255, 153, 153));
        tab5.setPreferredSize(new java.awt.Dimension(176, 48));
        tab5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab5MouseClicked(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setText("Chi Tiết Hóa Đơn");

        javax.swing.GroupLayout tab5Layout = new javax.swing.GroupLayout(tab5);
        tab5.setLayout(tab5Layout);
        tab5Layout.setHorizontalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab5Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        tab5Layout.setVerticalGroup(
            tab5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        tab6.setBackground(new java.awt.Color(255, 153, 153));
        tab6.setPreferredSize(new java.awt.Dimension(176, 48));
        tab6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab6MouseClicked(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Home");
        jLabel32.setPreferredSize(new java.awt.Dimension(176, 48));

        javax.swing.GroupLayout tab6Layout = new javax.swing.GroupLayout(tab6);
        tab6.setLayout(tab6Layout);
        tab6Layout.setHorizontalGroup(
            tab6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab6Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tab6Layout.setVerticalGroup(
            tab6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tab5, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
            .addComponent(tab3, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
            .addComponent(tab2, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
            .addComponent(tab4, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
            .addComponent(tab6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(tab6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tab4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new javax.swing.OverlayLayout(jPanel7));

        jp2.setBackground(new java.awt.Color(176, 134, 62));

        table_HD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_HD);

        btn_SuaHD.setBackground(new java.awt.Color(204, 51, 0));
        btn_SuaHD.setForeground(new java.awt.Color(255, 255, 255));
        btn_SuaHD.setText("Cập Nhật");
        btn_SuaHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_SuaHDMouseClicked(evt);
            }
        });

        btn_themHD.setBackground(new java.awt.Color(204, 51, 0));
        btn_themHD.setForeground(new java.awt.Color(255, 255, 255));
        btn_themHD.setText("Thêm");
        btn_themHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themHDMouseClicked(evt);
            }
        });

        btn_showHD.setText("Refresh");
        btn_showHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_showHDMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("MAHD");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Ngày Lập");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hình Thức Thanh Toán");

        jLabel9.setFont(new java.awt.Font("VNtimes new roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("MAKH");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("MAKM");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("MANV");

        jTextField6.setText("jTextField1");

        jTextField7.setText("jTextField1");

        javax.swing.GroupLayout jp2Layout = new javax.swing.GroupLayout(jp2);
        jp2.setLayout(jp2Layout);
        jp2Layout.setHorizontalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(btn_showHD)
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_SuaHD)
                            .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)))
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_HTTT)
                                        .addComponent(txt_MAKM)
                                        .addComponent(txt_MANV)
                                        .addComponent(txt_MAHD)
                                        .addComponent(btn_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_MAKH, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jp2Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(btn_themHD)))))
                .addContainerGap(277, Short.MAX_VALUE))
            .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                    .addContainerGap(492, Short.MAX_VALUE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(235, 235, 235)))
            .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                    .addContainerGap(502, Short.MAX_VALUE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(225, 225, 225)))
        );
        jp2Layout.setVerticalGroup(
            jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_showHD))
                .addGap(37, 37, 37)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addComponent(txt_MAHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel7)))
                .addGap(33, 33, 33)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_HTTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(39, 39, 39)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MAKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txt_MAKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_MANV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_SuaHD)
                    .addComponent(btn_themHD))
                .addGap(32, 32, 32))
            .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jp2Layout.createSequentialGroup()
                    .addGap(348, 348, 348)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(370, Short.MAX_VALUE)))
            .addGroup(jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp2Layout.createSequentialGroup()
                    .addContainerGap(376, Short.MAX_VALUE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(342, 342, 342)))
        );

        jPanel7.add(jp2);

        jp4.setBackground(new java.awt.Color(51, 153, 0));
        jp4.setPreferredSize(new java.awt.Dimension(1014, 718));

        btn_showKM.setText("Refresh");
        btn_showKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_showKMMouseClicked(evt);
            }
        });

        table_KM.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(table_KM);

        btn_themKM.setText("Thêm");
        btn_themKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themKMMouseClicked(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Tên Khuyến Mãi");

        jLabel26.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("MAKM");

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Tỉ Lệ");

        btn_capnhatKM.setText("Cập Nhật");
        btn_capnhatKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_capnhatKMMouseClicked(evt);
            }
        });

        btn_xoaKM.setText("Xóa");
        btn_xoaKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_xoaKMMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp4Layout = new javax.swing.GroupLayout(jp4);
        jp4.setLayout(jp4Layout);
        jp4Layout.setHorizontalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(btn_showKM)
                .addGap(26, 26, 26)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_themKM))
                        .addGap(49, 49, 49)
                        .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp4Layout.createSequentialGroup()
                                .addComponent(btn_capnhatKM)
                                .addGap(94, 94, 94)
                                .addComponent(btn_xoaKM))
                            .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_makm)
                                .addComponent(txt_tile)
                                .addComponent(txt_tenkm, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)))))
                .addContainerGap(339, Short.MAX_VALUE))
        );
        jp4Layout.setVerticalGroup(
            jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_showKM)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_makm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                    .addGroup(jp4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_tile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tenkm, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_themKM)
                    .addComponent(btn_capnhatKM)
                    .addComponent(btn_xoaKM))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jPanel7.add(jp4);

        jp3.setBackground(new java.awt.Color(153, 0, 153));

        btn_showKH.setText("Refresh");
        btn_showKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_showKHMouseClicked(evt);
            }
        });

        table_KH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(table_KH);

        btn_ThemKH.setText("Thêm");
        btn_ThemKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThemKHMouseClicked(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("MAKH");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Giới Tính");

        jLabel21.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Số Điện Thoại");

        jLabel22.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Điểm Tích Lũy");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Tên Khách Hàng");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Hạn Sử Dụng");

        btn_suaKH.setText("Sửa");
        btn_suaKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_suaKHMouseClicked(evt);
            }
        });

        btn_xoakh.setText("Xóa");
        btn_xoakh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_xoakhMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp3Layout = new javax.swing.GroupLayout(jp3);
        jp3.setLayout(jp3Layout);
        jp3Layout.setHorizontalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(btn_showKH)
                .addGap(18, 18, 18)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addComponent(btn_ThemKH)
                        .addGap(158, 158, 158)
                        .addComponent(btn_suaKH)
                        .addGap(183, 183, 183)
                        .addComponent(btn_xoakh))
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel22)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(98, 98, 98)
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(chooser_KH, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                            .addComponent(txt_makh)
                            .addComponent(txt_tenkh)
                            .addComponent(txt_GT)
                            .addComponent(txt_sdt)
                            .addComponent(txt_diemtluy))))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jp3Layout.setVerticalGroup(
            jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp3Layout.createSequentialGroup()
                        .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_showKH))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_makh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_GT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_diemtluy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chooser_KH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ThemKH)
                    .addComponent(btn_suaKH)
                    .addComponent(btn_xoakh))
                .addGap(83, 83, 83))
        );

        jPanel7.add(jp3);

        jp1.setBackground(new java.awt.Color(197, 80, 110));

        btn_showTD.setText("Refresh");
        btn_showTD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_showTDMouseClicked(evt);
            }
        });

        table_TD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table_TD);

        btn_ThemTD.setText("Thêm");
        btn_ThemTD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ThemTDMouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("MATD");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Tên Món");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Giá");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Trạng Thái");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Kích Cỡ");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Mô tả");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Mã Loại");

        btn_CapNhatTD.setText("Cập Nhật");
        btn_CapNhatTD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_CapNhatTDMouseClicked(evt);
            }
        });

        btn_xoaTD.setText("Xóa");
        btn_xoaTD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_xoaTDMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp1Layout = new javax.swing.GroupLayout(jp1);
        jp1.setLayout(jp1Layout);
        jp1Layout.setHorizontalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addComponent(btn_ThemTD)
                        .addGap(166, 166, 166)
                        .addComponent(btn_CapNhatTD, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(btn_xoaTD)
                        .addGap(131, 131, 131))
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_mota, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                            .addGroup(jp1Layout.createSequentialGroup()
                                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txt_ml, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                    .addComponent(txt_tenmon, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_gia, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_matd, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_kc, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_TT))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(146, 146, 146))
            .addGroup(jp1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btn_showTD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp1Layout.setVerticalGroup(
            jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_showTD)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addComponent(txt_matd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_tenmon, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)))
                .addGap(18, 18, 18)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_gia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_kc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_TT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_ml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_mota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_ThemTD)
                    .addGroup(jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_CapNhatTD, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_xoaTD)))
                .addGap(21, 21, 21))
        );

        jPanel7.add(jp1);

        jp5.setBackground(new java.awt.Color(0, 204, 204));

        table_CTHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(table_CTHD);

        btn_themcthd.setText("Thêm");
        btn_themcthd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_themcthdMouseClicked(evt);
            }
        });

        btn_showCTHD.setText("Refresh");

        jLabel29.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(242, 242, 242));
        jLabel29.setText("Số Lượng");

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(242, 242, 242));
        jLabel30.setText("Mã Hóa Đơn");

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(242, 242, 242));
        jLabel31.setText("Mã Thực Đơn");

        javax.swing.GroupLayout jp5Layout = new javax.swing.GroupLayout(jp5);
        jp5.setLayout(jp5Layout);
        jp5Layout.setHorizontalGroup(
            jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp5Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp5Layout.createSequentialGroup()
                        .addComponent(btn_showCTHD)
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp5Layout.createSequentialGroup()
                        .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addGap(76, 76, 76)
                        .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_macthdtd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_macthd, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_sl, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(356, 356, 356))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp5Layout.createSequentialGroup()
                        .addComponent(btn_themcthd)
                        .addGap(467, 467, 467))))
        );
        jp5Layout.setVerticalGroup(
            jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_showCTHD))
                .addGap(18, 18, 18)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(txt_sl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(txt_macthd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txt_macthdtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_themcthd)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        jPanel7.add(jp5);

        javax.swing.GroupLayout jp6Layout = new javax.swing.GroupLayout(jp6);
        jp6.setLayout(jp6Layout);
        jp6Layout.setHorizontalGroup(
            jp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1014, Short.MAX_VALUE)
        );
        jp6Layout.setVerticalGroup(
            jp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );

        jPanel7.add(jp6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//định dạng kiểu dữ liệu raw
    class RawRenderer extends DefaultTableCellRenderer {

        public RawRenderer() {
            super();
        }

        public void setValue(Object value) {
            if (value instanceof byte[]) {
                byte[] rawValue = (byte[]) value;
                setText(javax.xml.bind.DatatypeConverter.printHexBinary(rawValue));
            } else {
                super.setValue(value);
            }
        }
    }
//định dạng cột table kiểu float
    class FloatRenderer extends DefaultTableCellRenderer {
        
    private final DecimalFormat FORMAT = new DecimalFormat("#.##");

    public FloatRenderer() {
        super();
    }

    public void setValue(Object value) {
        if (value instanceof Float) {
            float floatValue = (Float) value;
            setText(FORMAT.format(floatValue));
        } else {
            super.setValue(value);
        }
    }
}

    
    private void tab1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab1MouseClicked
        jp2.setVisible(true);
        jp1.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);
        tab1.setBackground(Color.LIGHT_GRAY);
        tab2.setBackground(new Color(255, 153, 153));
        tab3.setBackground(new Color(255, 153, 153));
        tab4.setBackground(new Color(255, 153, 153));
        tab5.setBackground(new Color(255, 153, 153));
        table_HD.getModel();
        // TODO add your handling code here:
    }//GEN-LAST:event_tab1MouseClicked

    private void tab2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab2MouseClicked
        jp1.setVisible(true);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);
        tab2.setBackground(Color.LIGHT_GRAY);
        tab1.setBackground(new Color(255, 153, 153));
        tab3.setBackground(new Color(255, 153, 153));
        tab4.setBackground(new Color(255, 153, 153));
        tab5.setBackground(new Color(255, 153, 153));
        // TODO add your handling code here:
        table_TD.getModel();
    }//GEN-LAST:event_tab2MouseClicked

    private void tab3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab3MouseClicked
        jp3.setVisible(true);
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);
        tab3.setBackground(Color.LIGHT_GRAY);
        tab1.setBackground(new Color(255, 153, 153));
        tab2.setBackground(new Color(255, 153, 153));
        tab4.setBackground(new Color(255, 153, 153));
        tab5.setBackground(new Color(255, 153, 153));
        table_KH.getModel();
        // TODO add your handling code here:
    }//GEN-LAST:event_tab3MouseClicked

    private void tab4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab4MouseClicked
        jp4.setVisible(true);
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp5.setVisible(false);
        tab4.setBackground(Color.LIGHT_GRAY);
        tab1.setBackground(new Color(255, 153, 153));
        tab2.setBackground(new Color(255, 153, 153));
        tab3.setBackground(new Color(255, 153, 153));
        tab5.setBackground(new Color(255, 153, 153));
        // TODO add your handling code here:
        table_KM.getModel();
    }//GEN-LAST:event_tab4MouseClicked

    private void btn_SuaHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_SuaHDMouseClicked
        // TODO add your handling code here:
        Date date = null;
        if (btn_Date != null) {
            date = btn_Date.getDate();
        }
        if (date == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày tháng năm.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else if (txt_HTTT.getText().isEmpty() || txt_MAKH.getText().isEmpty() || txt_MAKM.getText().isEmpty() || txt_MANV.getText().isEmpty() || txt_MAHD.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa cung cấp đủ thông tin! Vui lòng nhập đầy đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            if (demSoLanCapNhat < 2) {
                if (t.updateHD(dateFormat.format(date), txt_HTTT.getText(), txt_MAKH.getText(), txt_MAKM.getText(), txt_MANV.getText(), txt_MAHD.getText())) {
                    demSoLanCapNhat++;

                    JOptionPane.showMessageDialog(this, "Cập nhật thành công !", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txt_MAHD.setText("");
                    btn_Date.setDate(null);
                    txt_HTTT.setText("");
                    txt_MAKH.setText("");
                    txt_MAKM.setText("");
                    txt_MANV.setText("");

                    if (demSoLanCapNhat >= 2) {
                        JOptionPane.showMessageDialog(this, "Bạn đã cập nhật thành công 2 lần và bạn không cập nhật được nữa!", "Cảnh báo", JOptionPane.INFORMATION_MESSAGE);
                    }

                }
            } else {
                JOptionPane.showMessageDialog(this, "Đã đạt giới hạn cập nhật (2 lần). Không thể cập nhật.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

    }//GEN-LAST:event_btn_SuaHDMouseClicked
//Hiện thị dữ liệu Hóa Đơn
    private void btn_showHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showHDMouseClicked
        ArrayList arr = null;
        DefaultTableModel model = (DefaultTableModel) table_HD.getModel();
        if (arr == null) {
            arr = x.showDataHoaDon();
        }

        Object[] columnNames = (Object[]) arr.get(0);
        Object[][] data = (Object[][]) arr.get(1);

        model.setDataVector(data, columnNames);
        // Lấy đối tượng cell renderer của cột ngày tạo hóa đơn
        TableColumnModel columnModel = table_HD.getColumnModel();
        TableColumn column = columnModel.getColumn(1); // ví dụ cột 2 là cột ngày tạo hóa đơn
        TableCellRenderer renderer = new DefaultTableCellRenderer();

        // Định dạng lại ngày tháng năm cho cell renderer
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        ((DefaultTableCellRenderer) renderer).setHorizontalAlignment(JLabel.CENTER);

        // Thiết lập giá trị mới cho cell renderer
        column.setCellRenderer(new TableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) renderer.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (value instanceof Date) {
                    label.setText(dateFormat.format(value));
                }
                return label;
            }
        });

    }//GEN-LAST:event_btn_showHDMouseClicked

    private void btn_themHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themHDMouseClicked
        // TODO add your handling code here:
        Date date = null;
        if (btn_Date != null) {
            date = btn_Date.getDate();
        }
        if (date == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày tháng năm.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else if (txt_HTTT.getText().isEmpty() || txt_MAKH.getText().isEmpty() || txt_MAKM.getText().isEmpty() || txt_MANV.getText().isEmpty() || txt_MAHD.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa cung cấp đủ thông tin! Vui lòng nhập đầy đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
            if (demSoLanThem < 2) {
                if (t.insertHD(dateFormat.format(date), txt_HTTT.getText(), txt_MAKH.getText(), txt_MAKM.getText(), txt_MANV.getText(), txt_MAHD.getText())) {
                    demSoLanThem++;

                    JOptionPane.showMessageDialog(this, "Thêm thành công !", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txt_MAHD.setText("");
                    btn_Date.setDate(null);
                    txt_HTTT.setText("");
                    txt_MAKH.setText("");
                    txt_MAKM.setText("");
                    txt_MANV.setText("");

                    if (demSoLanThem >= 2) {
                        JOptionPane.showMessageDialog(this, "Bạn đã thêm thành công 2 lần và bạn không thêm được nữa!", "Cảnh báo", JOptionPane.INFORMATION_MESSAGE);

                    }

                }
            } else {
                JOptionPane.showMessageDialog(this, "Đã đạt giới hạn Thêm (2 lần). Không thể Thêm.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_btn_themHDMouseClicked
    //Hiện thị dữ liệu Thực Đơn
    private void btn_showTDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showTDMouseClicked
        ArrayList arr = null;
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_TD.getModel();
        if (arr == null) {
            arr = x.showDataThuDon();
        }

        Object[] columnNames = (Object[]) arr.get(0);
        Object[][] data = (Object[][]) arr.get(1);

        model.setDataVector(data, columnNames);
        TableColumn rawColumn = table_TD.getColumn("TRANGTHAI"); // Lấy cột raw từ JTable
        rawColumn.setCellRenderer(new RawRenderer()); // Đặt Renderer cho cột raw
        TableColumn floatColumn = table_TD.getColumn("GIA"); // Lấy cột float từ JTable
        floatColumn.setCellRenderer(new FloatRenderer()); // Đặt Renderer cho cột float

    }//GEN-LAST:event_btn_showTDMouseClicked

    private void btn_ThemTDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThemTDMouseClicked
        // TODO add your handling code here:
        if (txt_matd.getText().isEmpty() || txt_tenmon.getText().isEmpty() || txt_gia.getText().isEmpty() || txt_kc.getText().isEmpty() || txt_TT.getText().isEmpty()|| txt_mota.getText().isEmpty()|| txt_ml.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa cung cấp đủ thông tin! Vui lòng nhập đầy đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            if (demSoLanThem < 2) {
                if (t.insertTD(txt_matd.getText(), txt_tenmon.getText(), txt_gia.getText(), txt_kc.getText(), txt_TT.getText(), txt_mota.getText(),txt_ml.getText())) {
                    demSoLanThem++;

                    JOptionPane.showMessageDialog(this, "Thêm thành công !", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txt_matd.setText("");
                    txt_tenmon.setText("");
                    txt_gia.setText("");
                    txt_kc.setText("");
                    txt_TT.setText("");
                    txt_mota.setText("");
                    txt_ml.setText("");

                    if (demSoLanThem >= 2) {
                        JOptionPane.showMessageDialog(this, "Bạn đã thêm thành công 2 lần và bạn không thêm được nữa!", "Cảnh báo", JOptionPane.INFORMATION_MESSAGE);

                    }

                }
            } else {
                JOptionPane.showMessageDialog(this, "Đã đạt giới hạn Thêm (2 lần). Không thể Thêm.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_btn_ThemTDMouseClicked

    private void btn_CapNhatTDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CapNhatTDMouseClicked
            // TODO add your handling code here:
        if (txt_tenmon.getText().isEmpty() || txt_gia.getText().isEmpty() || txt_kc.getText().isEmpty() || txt_TT.getText().isEmpty() || txt_matd.getText().isEmpty() || txt_mota.getText().isEmpty() || txt_ml.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa cung cấp đủ thông tin! Vui lòng nhập đầy đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            if (demSoLanCapNhat < 2) {
                if (t.updateTD(txt_tenmon.getText(),txt_gia.getText(), txt_kc.getText(), txt_TT.getText(), txt_mota.getText(), txt_ml.getText(), txt_matd.getText())) {
                    demSoLanCapNhat++;

                    JOptionPane.showMessageDialog(this, "Cập nhật thành công !", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txt_matd.setText("");
                    txt_tenmon.setText("");
                    txt_gia.setText("");
                    txt_kc.setText("");
                    txt_TT.setText("");
                    txt_mota.setText("");
                    txt_ml.setText("");

                    if (demSoLanCapNhat >= 2) {
                        JOptionPane.showMessageDialog(this, "Bạn đã cập nhật thành công 2 lần và bạn không cập nhật được nữa!", "Cảnh báo", JOptionPane.INFORMATION_MESSAGE);
                    }

                }
            } else {
                JOptionPane.showMessageDialog(this, "Đã đạt giới hạn cập nhật (2 lần). Không thể Cập Nhật.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

    }//GEN-LAST:event_btn_CapNhatTDMouseClicked

    private void btn_xoaTDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_xoaTDMouseClicked
        // TODO add your handling code here:
        if ( txt_matd.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa cung cấp đủ thông tin! Vui lòng nhập đầy đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            if (demSoLanXoa < 2) {
                if (t.deleteTD( txt_matd.getText())) {
                    demSoLanXoa++;

                    JOptionPane.showMessageDialog(this, "Xóa thành công !", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txt_matd.setText("");
       

                    if (demSoLanXoa >= 2) {
                        JOptionPane.showMessageDialog(this, "Bạn đã xóa thành công 2 lần và bạn không xóa được nữa!", "Cảnh báo", JOptionPane.INFORMATION_MESSAGE);
                    }

                }
            } else {
                JOptionPane.showMessageDialog(this, "Đã đạt giới hạn xóa (2 lần). Không thể Xóa.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_btn_xoaTDMouseClicked

    private void btn_showKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showKHMouseClicked
        // TODO add your handling code here:
        ArrayList arr = null;
        DefaultTableModel model = (DefaultTableModel) table_KH.getModel();
        if (arr == null) {
            arr = x.showDataKhachHang();
        }

        Object[] columnNames = (Object[]) arr.get(0);
        Object[][] data = (Object[][]) arr.get(1);

        model.setDataVector(data, columnNames);
        // Lấy đối tượng cell renderer của cột ngày tạo hóa đơn
        TableColumnModel columnModel = table_KH.getColumnModel();
        TableColumn column = columnModel.getColumn(5);
        TableCellRenderer renderer = new DefaultTableCellRenderer();

        // Định dạng lại ngày tháng năm cho cell renderer
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        ((DefaultTableCellRenderer) renderer).setHorizontalAlignment(JLabel.CENTER);

        // Thiết lập giá trị mới cho cell renderer
        column.setCellRenderer(new TableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                JLabel label = (JLabel) renderer.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (value instanceof Date) {
                    label.setText(dateFormat.format(value));
                }
                return label;
            }
        });
    }//GEN-LAST:event_btn_showKHMouseClicked

    private void btn_ThemKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ThemKHMouseClicked
        // TODO add your handling code here:
        Date date = null;
        if (chooser_KH != null) {
            date = chooser_KH.getDate();
        }
        if (date == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày tháng năm.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else if (txt_makh.getText().isEmpty() || txt_tenkh.getText().isEmpty() || txt_GT.getText().isEmpty() || txt_sdt.getText().isEmpty() || txt_diemtluy.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa cung cấp đủ thông tin! Vui lòng nhập đầy đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            if (demSoLanThem < 2) {
                if (t.insertKH(txt_makh.getText(), txt_tenkh.getText(), txt_GT.getText(), txt_sdt.getText(), txt_diemtluy.getText(),dateFormat.format(date))) {
                    demSoLanThem++;

                    JOptionPane.showMessageDialog(this, "Thêm thành công !", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txt_makh.setText("");
                    chooser_KH.setDate(null);
                    txt_tenkh.setText("");
                    txt_GT.setText("");
                    txt_sdt.setText("");
                    txt_diemtluy.setText("");
                    

                    if (demSoLanThem >= 2) {
                        JOptionPane.showMessageDialog(this, "Bạn đã thêm thành công 2 lần và bạn không Thêm được nữa!", "Cảnh báo", JOptionPane.INFORMATION_MESSAGE);
                    }

                }
            } else {
                JOptionPane.showMessageDialog(this, "Đã đạt giới hạn Thêm (2 lần). Không thể Thêm.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_btn_ThemKHMouseClicked

    private void btn_suaKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_suaKHMouseClicked

        // TODO add your handling code here:
        Date date = null;
        if (chooser_KH != null) {
            date = chooser_KH.getDate();
        }
        if (date == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày tháng năm.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else if (txt_makh.getText().isEmpty() || txt_tenkh.getText().isEmpty() || txt_GT.getText().isEmpty() || txt_sdt.getText().isEmpty() || txt_diemtluy.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa cung cấp đủ thông tin! Vui lòng nhập đầy đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            if (demSoLanCapNhat < 2) {
                if (t.updateKH(txt_tenkh.getText(), txt_GT.getText(), txt_sdt.getText(), txt_diemtluy.getText(),dateFormat.format(date),txt_makh.getText())) {
                    demSoLanCapNhat++;

                    JOptionPane.showMessageDialog(this, "Cập nhật thành công !", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txt_makh.setText("");
                    chooser_KH.setDate(null);
                    txt_tenkh.setText("");
                    txt_GT.setText("");
                    txt_sdt.setText("");
                    txt_diemtluy.setText("");
                    

                    if (demSoLanCapNhat >= 2) {
                        JOptionPane.showMessageDialog(this, "Bạn đã cập nhật thành công 2 lần và bạn không cập nhật được nữa!", "Cảnh báo", JOptionPane.INFORMATION_MESSAGE);
                    }

                }
            } else {
                JOptionPane.showMessageDialog(this, "Đã đạt giới hạn cập nhật (2 lần). Không thể cập nhật.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
        }
        
    }//GEN-LAST:event_btn_suaKHMouseClicked

    private void btn_xoakhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_xoakhMouseClicked
        // TODO add your handling code here:
        if ( txt_makh.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa cung cấp đủ thông tin! Vui lòng nhập đầy đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            if (demSoLanXoa < 2) {
                if (t.deleteKH(txt_makh.getText())) {
                    demSoLanXoa++;

                    JOptionPane.showMessageDialog(this, "Xóa thành công !", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txt_makh.setText("");

                    if (demSoLanXoa >= 2) {
                        JOptionPane.showMessageDialog(this, "Bạn đã Xóa thành công 2 lần và bạn không xóa được nữa!", "Cảnh báo", JOptionPane.INFORMATION_MESSAGE);
                    }

                }
            } else {
                JOptionPane.showMessageDialog(this, "Đã đạt giới hạn xóa (2 lần). Không thể Xóa.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_btn_xoakhMouseClicked

    private void btn_showKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_showKMMouseClicked
        // TODO add your handling code here:
        ArrayList arr = null;
        DefaultTableModel model = (DefaultTableModel) table_KM.getModel();
        if (arr == null) {
            arr = x.showDataKhuyenMai();
        }

        Object[] columnNames = (Object[]) arr.get(0);
        Object[][] data = (Object[][]) arr.get(1);

        model.setDataVector(data, columnNames);
    }//GEN-LAST:event_btn_showKMMouseClicked

    private void btn_themKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themKMMouseClicked
        // TODO add your handling code here:
        if (txt_makm.getText().isEmpty() || txt_tenkm.getText().isEmpty() || txt_tile.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa cung cấp đủ thông tin! Vui lòng nhập đầy đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            if (demSoLanThem < 2) {
                if (t.insertKM(txt_makm.getText(), txt_tenkm.getText(), txt_tile.getText())) {
                    demSoLanThem++;

                    JOptionPane.showMessageDialog(this, "Thêm thành công !", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txt_makm.setText("");
                    txt_tenkm.setText("");
                    txt_tile.setText("");

                    if (demSoLanThem >= 2) {
                        JOptionPane.showMessageDialog(this, "Bạn đã thêm thành công 2 lần và bạn không thêm được nữa!", "Cảnh báo", JOptionPane.INFORMATION_MESSAGE);

                    }

                }
            } else {
                JOptionPane.showMessageDialog(this, "Đã đạt giới hạn Thêm (2 lần). Không thể Thêm.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_btn_themKMMouseClicked

    private void btn_capnhatKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_capnhatKMMouseClicked
        // TODO add your handling code here:
        if (txt_makm.getText().isEmpty() || txt_tenkm.getText().isEmpty() || txt_tile.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa cung cấp đủ thông tin! Vui lòng nhập đầy đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            if (demSoLanCapNhat < 2) {
                if (t.updateKM(txt_tile.getText(), txt_tenkm.getText(),txt_makm.getText() )) {
                    demSoLanCapNhat++;

                    JOptionPane.showMessageDialog(this, "Cập nhật thành công !", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txt_makm.setText("");
                    txt_tenkm.setText("");
                    txt_tile.setText("");

                    if (demSoLanCapNhat >= 2) {
                        JOptionPane.showMessageDialog(this, "Bạn đã cập nhật thành công 2 lần và bạn không cập nhật được nữa!", "Cảnh báo", JOptionPane.INFORMATION_MESSAGE);
                    }

                }
            } else {
                JOptionPane.showMessageDialog(this, "Đã đạt giới hạn cập nhật (2 lần). Không thể Cập Nhật.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_btn_capnhatKMMouseClicked

    private void btn_xoaKMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_xoaKMMouseClicked
        // TODO add your handling code here:
        if ( txt_makm.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa cung cấp đủ thông tin! Vui lòng nhập đầy đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            if (demSoLanXoa < 2) {
                if (t.deleteKM(txt_makm.getText())) {
                    demSoLanXoa++;

                    JOptionPane.showMessageDialog(this, "Xóa thành công !", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txt_makm.setText("");

                    if (demSoLanXoa >= 2) {
                        JOptionPane.showMessageDialog(this, "Bạn đã Xóa thành công 2 lần và bạn không xóa được nữa!", "Cảnh báo", JOptionPane.INFORMATION_MESSAGE);
                    }

                }
            } else {
                JOptionPane.showMessageDialog(this, "Đã đạt giới hạn xóa (2 lần). Không thể Xóa.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_btn_xoaKMMouseClicked

    private void tab5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab5MouseClicked
        // TODO add your handling code here:
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(true);
        tab5.setBackground(Color.LIGHT_GRAY);
        tab1.setBackground(new Color(255, 153, 153));
        tab3.setBackground(new Color(255, 153, 153));
        tab4.setBackground(new Color(255, 153, 153));
        tab2.setBackground(new Color(255, 153, 153));
        // TODO add your handling code here:
        table_CTHD.getModel();
    }//GEN-LAST:event_tab5MouseClicked

    private void btn_themcthdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_themcthdMouseClicked
        // TODO add your handling code here:
        if (txt_matd.getText().isEmpty() || txt_sl.getText().isEmpty() || txt_macthd.getText().isEmpty() || txt_macthdtd.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Bạn chưa cung cấp đủ thông tin! Vui lòng nhập đầy đủ thông tin.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        } else {
            if (demSoLanThem < 2) {
                if (t.insertCTHD(txt_sl.getText(), txt_macthd.getText(),txt_macthdtd.getText())) {
                    demSoLanThem++;

                    JOptionPane.showMessageDialog(this, "Thêm thành công !", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                    txt_sl.setText("");
                    txt_macthd.setText("");
                    txt_macthdtd.setText("");
                    if (demSoLanThem >= 2) {
                        JOptionPane.showMessageDialog(this, "Bạn đã thêm thành công 2 lần và bạn không thêm được nữa!", "Cảnh báo", JOptionPane.INFORMATION_MESSAGE);

                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "Đã đạt giới hạn Thêm (2 lần). Không thể Thêm.", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }//GEN-LAST:event_btn_themcthdMouseClicked

    private void tab6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab6MouseClicked
        // TODO add your handling code here:
        jp1.setVisible(false);
        jp2.setVisible(false);
        jp3.setVisible(false);
        jp4.setVisible(false);
        jp5.setVisible(false);
        
        tab2.setBackground(Color.LIGHT_GRAY);
        tab1.setBackground(new Color(255, 153, 153));
        tab3.setBackground(new Color(255, 153, 153));
        tab4.setBackground(new Color(255, 153, 153));
        tab5.setBackground(new Color(255, 153, 153));
        // TODO add your handling code here:
        table_TD.getModel();
    }//GEN-LAST:event_tab6MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CapNhatTD;
    private com.toedter.calendar.JDateChooser btn_Date;
    private javax.swing.JButton btn_SuaHD;
    private javax.swing.JButton btn_ThemKH;
    private javax.swing.JButton btn_ThemTD;
    private javax.swing.JButton btn_capnhatKM;
    private javax.swing.JButton btn_showCTHD;
    private javax.swing.JButton btn_showHD;
    private javax.swing.JButton btn_showKH;
    private javax.swing.JButton btn_showKM;
    private javax.swing.JButton btn_showTD;
    private javax.swing.JButton btn_suaKH;
    private javax.swing.JButton btn_themHD;
    private javax.swing.JButton btn_themKM;
    private javax.swing.JButton btn_themcthd;
    private javax.swing.JButton btn_xoaKM;
    private javax.swing.JButton btn_xoaTD;
    private javax.swing.JButton btn_xoakh;
    private com.toedter.calendar.JDateChooser chooser_KH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel jp1;
    private javax.swing.JPanel jp2;
    private javax.swing.JPanel jp3;
    private javax.swing.JPanel jp4;
    private javax.swing.JPanel jp5;
    private javax.swing.JPanel jp6;
    private javax.swing.JPanel tab1;
    private javax.swing.JPanel tab2;
    private javax.swing.JPanel tab3;
    private javax.swing.JPanel tab4;
    private javax.swing.JPanel tab5;
    private javax.swing.JPanel tab6;
    private javax.swing.JTable table_CTHD;
    private javax.swing.JTable table_HD;
    private javax.swing.JTable table_KH;
    private javax.swing.JTable table_KM;
    private javax.swing.JTable table_TD;
    private javax.swing.JTextField txt_GT;
    private javax.swing.JTextField txt_HTTT;
    private javax.swing.JTextField txt_MAHD;
    private javax.swing.JTextField txt_MAKH;
    private javax.swing.JTextField txt_MAKM;
    private javax.swing.JTextField txt_MANV;
    private javax.swing.JTextField txt_TT;
    private javax.swing.JTextField txt_diemtluy;
    private javax.swing.JTextField txt_gia;
    private javax.swing.JTextField txt_kc;
    private javax.swing.JTextField txt_macthd;
    private javax.swing.JTextField txt_macthdtd;
    private javax.swing.JTextField txt_makh;
    private javax.swing.JTextField txt_makm;
    private javax.swing.JTextField txt_matd;
    private javax.swing.JTextField txt_ml;
    private javax.swing.JTextField txt_mota;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_sl;
    private javax.swing.JTextField txt_tenkh;
    private javax.swing.JTextField txt_tenkm;
    private javax.swing.JTextField txt_tenmon;
    private javax.swing.JTextField txt_tile;
    // End of variables declaration//GEN-END:variables
}
