package GUI;

import BLL.GetData;
import BLL.ExecuteData;
import Ultilities.ConvertData.ConvertDataORCL;
import Ultilities.swing.ButtonColumn;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author phatl
 */
public class S_NumberOfSession extends javax.swing.JFrame {

    /**
     * Creates new form S_NumberOfSession
     */
    public S_NumberOfSession() {
        initComponents();
        showDataOnTable();
    }
   
    Action kill = new AbstractAction()
    {
        public void actionPerformed(ActionEvent e)
        {
            //remove row
            JTable table = (JTable)e.getSource();
            int indexRow = Integer.valueOf( e.getActionCommand() );
            
            String SID = table.getValueAt(indexRow, 1).toString();
            String SerialID = table.getValueAt(indexRow, 2).toString();
            if(ExecuteData.ExecuteSql(SID, SerialID))
            {
                JOptionPane.showMessageDialog(jTable1, "Kill session thành công !","Thông Báo",JOptionPane.INFORMATION_MESSAGE);
                ((DefaultTableModel)table.getModel()).removeRow(indexRow);
            }
            else
            {
                JOptionPane.showMessageDialog(jTable1, "Kill session thất bại !","Thông Báo",JOptionPane.ERROR_MESSAGE);
            }
        }
    };
    
    public void showDataOnTable()
    {
        
        GetData x = new GetData();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        ArrayList arr = x.showSessionCurrent();

        String[] columnNames = (String[])arr.get(0);
        String[][] data = ConvertDataORCL.ConvertObject2DToString2D((Object[][])arr.get(1));
        
        
        model.setDataVector(data, columnNames);
        
        model.addColumn("");
        ButtonColumn btnCol = new ButtonColumn(jTable1, kill, columnNames.length,"Kill");
        
        CountRecord.setText("Số Lượng Session: "+data.length);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CountRecord = new javax.swing.JLabel();
        Refresh_Session = new javax.swing.JButton();
        Demo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        CountRecord.setText("jLabel1");

        Refresh_Session.setBackground(new java.awt.Color(0, 204, 255));
        Refresh_Session.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Refresh_Session.setForeground(new java.awt.Color(0, 0, 0));
        Refresh_Session.setText("Làm Mới");
        Refresh_Session.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Refresh_SessionMouseClicked(evt);
            }
        });

        Demo.setBackground(new java.awt.Color(102, 153, 255));
        Demo.setForeground(new java.awt.Color(0, 0, 0));
        Demo.setText("Demo");
        Demo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DemoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CountRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Demo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Refresh_Session)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CountRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Refresh_Session)
                    .addComponent(Demo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Refresh_SessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Refresh_SessionMouseClicked
        showDataOnTable();
    }//GEN-LAST:event_Refresh_SessionMouseClicked

    private void DemoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DemoMouseClicked
        Demo_KillSession t = new Demo_KillSession();
        t.setVisible(true);
    }//GEN-LAST:event_DemoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CountRecord;
    private javax.swing.JButton Demo;
    private javax.swing.JButton Refresh_Session;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
