--------------------------------------------------------
--  File created - Thursday-March-02-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CHITIETHOADON
--------------------------------------------------------
  CREATE TABLE "CHITIETHOADON" 
   (	"SOLUONG" NUMBER(10,0), 
	"THANHTIEN" FLOAT(126), 
	"HOADONMAHD" VARCHAR2(10 BYTE), 
	"THUCDONMAMON" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CHITIETPHIEUNHAP
--------------------------------------------------------

  CREATE TABLE "CHITIETPHIEUNHAP" 
   (	"SOLUONG" NUMBER(10,0), 
	"GIANHAP" FLOAT(126), 
	"TENNCC" NVARCHAR2(255), 
	"NGAYNHAP" DATE, 
	"NGUYENLIEUMANL" VARCHAR2(10 BYTE), 
	"PHIEUNHAPMAPN" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CHITIETXUAT
--------------------------------------------------------

  CREATE TABLE "CHITIETXUAT" 
   (	"KHONGUYENLIEUMANL" VARCHAR2(10 BYTE), 
	"XUATNGUYENLIEUMAXUAT" VARCHAR2(10 BYTE), 
	"SOLUONG" NUMBER(10,0), 
	"DONVI" NVARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HOADON
--------------------------------------------------------

  CREATE TABLE "HOADON" 
   (	"MAHD" VARCHAR2(10 BYTE), 
	"NGAYLAP" DATE, 
	"TONGTIENVAT" FLOAT(126), 
	"HINHTHUC" VARCHAR2(100 BYTE), 
	"KHACHHANGMAKH" VARCHAR2(10 BYTE), 
	"KHUYENMAIMAKM" VARCHAR2(10 BYTE), 
	"NHANVIENMANV" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KHACHHANG
--------------------------------------------------------

  CREATE TABLE "KHACHHANG" 
   (	"MAKH" VARCHAR2(10 BYTE), 
	"TENKH" NVARCHAR2(255), 
	"GIOITINH" NVARCHAR2(5), 
	"SDT" VARCHAR2(10 BYTE), 
	"DIEMTICHLUY" NUMBER(10,0), 
	"HSD" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KHONGUYENLIEU
--------------------------------------------------------

  CREATE TABLE  "KHONGUYENLIEU" 
   (	"MANL" VARCHAR2(10 BYTE), 
	"TENNL" NVARCHAR2(255), 
	"SOLUONG" NUMBER(10,0), 
	"DONVI" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KHUYENMAI
--------------------------------------------------------

  CREATE TABLE "KHUYENMAI" 
   (	"MAKM" VARCHAR2(10 BYTE), 
	"TENKM" NVARCHAR2(255), 
	"TILE" FLOAT(10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NHANVIEN
--------------------------------------------------------

  CREATE TABLE  "NHANVIEN" 
   (	"MANV" VARCHAR2(10 BYTE), 
	"TENNV" NVARCHAR2(50), 
	"SDT" VARCHAR2(10 BYTE), 
	"GIOITINH" NVARCHAR2(5), 
	"TAIKHOAN" VARCHAR2(50 BYTE), 
	"ANHCANHAN" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("ANHCANHAN") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PHANLOAI 
--------------------------------------------------------

  CREATE TABLE "PHANLOAI" 
   (	"MALOAI" VARCHAR2(10 BYTE), 
	"TENLOAI" NVARCHAR2(255)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PHIEUNHAP
--------------------------------------------------------

  CREATE TABLE  "PHIEUNHAP" 
   (	"MAPN" VARCHAR2(10 BYTE), 
	"NGAYNHAP" DATE, 
	"NHANVIENMANV" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table THUCDON
--------------------------------------------------------

  CREATE TABLE "THUCDON" 
   (	"MAMON" VARCHAR2(10 BYTE), 
	"TENMON" NVARCHAR2(200), 
	"GIA" FLOAT(126), 
	"KICHCO" VARCHAR2(2 BYTE), 
	"TRANGTHAI" RAW(2), 
	"MOTA" NVARCHAR2(800), 
	"PHANLOAIMALOAI" VARCHAR2(10 BYTE), 
	"HINHANH" BLOB, 
	"VIDEOGIOITHIEU" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("HINHANH") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("VIDEOGIOITHIEU") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table XUATNGUYENLIEU
--------------------------------------------------------

  CREATE TABLE "XUATNGUYENLIEU" 
   (	"MAXUAT" VARCHAR2(10 BYTE), 
	"NGAYXUAT" DATE, 
	"NHANVIENMANV" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CHITIETHOADON
SET DEFINE OFF;
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (4,null,'HD001','TD002');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (2,null,'HD002','TD004');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (1,null,'HD003','TD001');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (7,null,'HD004','TD009');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (4,null,'HD005','TD008');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (2,null,'HD006','TD013');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (1,null,'HD007','TD015');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (4,null,'HD008','TD007');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (5,null,'HD009','TD028');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (2,null,'HD010','TD019');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (1,null,'HD011','TD021');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (4,null,'HD013','TD009');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (9,null,'HD014','TD005');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (4,null,'HD015','TD003');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (7,null,'HD016','TD011');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (9,null,'HD017','TD014');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (2,null,'HD018','TD012');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (6,null,'HD019','TD015');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (7,null,'HD020','TD022');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (3,null,'HD021','TD024');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (9,null,'HD022','TD023');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (3,null,'HD023','TD025');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (5,null,'HD024','TD026');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (6,null,'HD025','TD030');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (2,null,'HD026','TD027');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (4,null,'HD027','TD014');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (5,null,'HD028','TD029');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (1,null,'HD029','TD021');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (7,null,'HD030','TD007');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (6,null,'HD031','TD001');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (4,null,'HD032','TD005');
Insert into CHITIETHOADON (SOLUONG,THANHTIEN,HOADONMAHD,THUCDONMAMON) values (3,null,'HD033','TD010');

REM INSERTING into CHITIETPHIEUNHAP
SET DEFINE OFF;
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (300,60000000,'Công ty TNHH dịch vụ  Trung Nguyên',to_date('10-OCT-23','DD-MON-RR'),'NL001','PN001');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (150,3000000,'Công ty TNHH dịch vụ Vạn Phú Vĩnh An ',to_date('24-NOV-23','DD-MON-RR'),'NL002','PN002');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (30,450000,'Công ty TNHH dịch vụ XÂY DỰNG �?NH SAO',to_date('28-FEB-23','DD-MON-RR'),'NL003','PN003');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (20,520000,'Công ty TNHH dịch vụ Vinamilk',to_date('14-AUG-23','DD-MON-RR'),'NL004','PN004');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (15,600000,'Công ty TNHH dịch vụ Vinamilk',to_date('23-NOV-23','DD-MON-RR'),'NL005','PN005');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (20,1200000,'Công Ty TNHH Thương Mại Lá Phong',to_date('23-NOV-23','DD-MON-RR'),'NL006','PN006');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (50,1750000,'Công ty TNHH Dotea',to_date('22-OCT-23','DD-MON-RR'),'NL007','PN007');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (200,100000000,'Công ty TNHH dịch vụ  Trung Nguyên',to_date('10-DEC-23','DD-MON-RR'),'NL008','PN008');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (20,1400000,'Công ty TNHH dịch vụ Vinamilk',to_date('10-DEC-23','DD-MON-RR'),'NL009','PN009');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (20,1000000,'Công ty TNHH dịch vụ Vinamilk',to_date('10-DEC-23','DD-MON-RR'),'NL010','PN010');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (30,1350000,'Công ty TNHH dịch vụ Vinamilk',to_date('10-DEC-23','DD-MON-RR'),'NL011','PN011');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (30,1080000,' Công ty TNHH Thương Mại Lá Phong',to_date('28-FEB-23','DD-MON-RR'),'NL012','PN012');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (5,600000,'Công ty TNHH sản xuất bánh kẹo ',to_date('20-JUL-23','DD-MON-RR'),'NL013','PN013');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (5,650000,'Công ty TNHH sản xuất bánh kẹo ',to_date('25-DEC-23','DD-MON-RR'),'NL014','PN014');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (20,1350000,' Công ty TNHH Thương Mại Lá Phong',to_date('26-NOV-23','DD-MON-RR'),'NL015','PN015');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (10,480000,' Công ty TNHH Thương Mại Lá Phong',to_date('28-FEB-23','DD-MON-RR'),'NL016','PN016');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (15,100000000,'Công ty TNHH dịch vụ Vinamilk',to_date('22-SEP-23','DD-MON-RR'),'NL017','PN017');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (25,1625000,'Công ty TNHH dịch vụ Vinamilk',to_date('22-SEP-23','DD-MON-RR'),'NL018','PN018');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (15,825000,'Công ty TNHH dịch vụ Vinamilk',to_date('28-DEC-23','DD-MON-RR'),'NL019','PN019');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (15,1125000,'Công Ty TNHH Thương Mại Lá Phong',to_date('22-SEP-23','DD-MON-RR'),'NL020','PN020');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (25,625000,'Công ty TNHH dịch vụ Vinamilk',to_date('22-SEP-23','DD-MON-RR'),'NL021','PN021');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (20,980000,'Công ty TNHH Dotea',to_date('28-FEB-23','DD-MON-RR'),'NL022','PN022');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (25,1625000,'Công ty TNHH Dotea',to_date('23-NOV-23','DD-MON-RR'),'NL023','PN023');
Insert into CHITIETPHIEUNHAP (SOLUONG,GIANHAP,TENNCC,NGAYNHAP,NGUYENLIEUMANL,PHIEUNHAPMAPN) values (30,1350000,'Công ty TNHH Dotea',to_date('26-NOV-23','DD-MON-RR'),'NL024','PN024');
REM INSERTING into CHITIETXUAT
SET DEFINE OFF;
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL001','MX001',300,'Bao');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL002','MX002',150,'Bao');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL003','MX003',30,'Bao');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL004','MX004',20,'Lon');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL005','MX005',15,'Thùng');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL006','MX006',20,'Bao');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL007','MX007',50,'Hộp');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL008','MX008',200,'Bao');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL009','MX009',20,'Hộp');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL010','MX010',20,'Chai');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL011','MX011',30,'Chai');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL012','MX012',30,'Lon');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL013','MX013',5,'Thùng');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL014','MX014',5,'Thùng');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL015','MX015',20,'Lon');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL016','MX016',10,'Lon');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL017','MX017',15,'Chai');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL018','MX018',25,'Hộp');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL019','MX019',15,'Hộp');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL020','MX020',15,'Bao');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL021','MX021',25,'Bao');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL022','MX022',20,'Hộp');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL023','MX023',25,'Hộp');
Insert into CHITIETXUAT (KHONGUYENLIEUMANL,XUATNGUYENLIEUMAXUAT,SOLUONG,DONVI) values ('NL024','MX024',30,'Hộp');
REM INSERTING into HOADON
SET DEFINE OFF;
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD001',to_date('08-MAR-22','DD-MON-RR'),null,'Ti�?n mặt','KH001','KM003','NV001');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD002',to_date('08-MAR-22','DD-MON-RR'),null,'Ti�?n mặt','KH002','KM003','NV001');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD003',to_date('01-APR-22','DD-MON-RR'),null,'Ti�?n mặt','KH005',null,'NV004');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD004',to_date('09-APR-22','DD-MON-RR'),null,'Ti�?n mặt','KH004',null,'NV003');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD005',to_date('30-APR-22','DD-MON-RR'),null,'Chuyển khoản','KH005','KM004','NV005');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD006',to_date('30-APR-22','DD-MON-RR'),null,'Chuyển khoản','KH006','KM004','NV005');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD007',to_date('03-MAY-22','DD-MON-RR'),null,'Chuyển khoản','KH008',null,'NV003');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD008',to_date('19-MAY-22','DD-MON-RR'),null,'Chuyển khoản','KH008',null,'NV009');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD009',to_date('09-JUN-22','DD-MON-RR'),null,'Chuyển khoản','KH009',null,'NV007');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD010',to_date('18-JUN-22','DD-MON-RR'),null,'Ti�?n mặt','KH010',null,'NV010');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD011',to_date('16-JUL-22','DD-MON-RR'),null,'Ti�?n mặt','KH011',null,'NV008');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD012',to_date('17-AUG-22','DD-MON-RR'),null,'Chuyển khoản','KH002','KM005','NV003');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD013',to_date('29-SEP-22','DD-MON-RR'),null,'Chuyển khoản','KH013',null,'NV002');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD014',to_date('30-OCT-22','DD-MON-RR'),null,'Chuyển khoản','KH014',null,'NV001');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD015',to_date('15-NOV-22','DD-MON-RR'),null,'Ti�?n mặt','KH003','KM006','NV004');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD016',to_date('30-NOV-22','DD-MON-RR'),null,'Chuyển khoản','KH016','KM006','NV002');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD017',to_date('24-DEC-22','DD-MON-RR'),null,'Chuyển khoản','KH017','KM007','NV008');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD018',to_date('22-JAN-23','DD-MON-RR'),null,'Ti�?n mặt','KH018','KM001','NV003');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD019',to_date('22-JAN-23','DD-MON-RR'),null,'Chuyển khoản','KH009','KM001','NV003');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD020',to_date('23-JAN-23','DD-MON-RR'),null,'Ti�?n mặt','KH006','KM001','NV005');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD021',to_date('23-JAN-23','DD-MON-RR'),null,'Chuyển khoản','KH010','KM001','NV005');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD022',to_date('23-JAN-23','DD-MON-RR'),null,'Ti�?n mặt','KH017','KM001','NV005');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD023',to_date('23-JAN-23','DD-MON-RR'),null,'Ti�?n mặt','KH015','KM001','NV005');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD024',to_date('23-JAN-23','DD-MON-RR'),null,'Ti�?n mặt','KH003','KM001','NV005');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD025',to_date('24-JAN-23','DD-MON-RR'),null,'Ti�?n mặt','KH020','KM001','NV008');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD026',to_date('24-JAN-23','DD-MON-RR'),null,'Chuyển khoản','KH019','KM001','NV008');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD027',to_date('25-JAN-23','DD-MON-RR'),null,'Ti�?n mặt','KH018',null,'NV007');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD028',to_date('26-JAN-23','DD-MON-RR'),null,'Ti�?n mặt','KH005',null,'NV004');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD029',to_date('26-JAN-23','DD-MON-RR'),null,'Ti�?n mặt','KH006',null,'NV004');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD030',to_date('28-JAN-23','DD-MON-RR'),null,'Ti�?n mặt','KH003',null,'NV007');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD031',to_date('14-FEB-23','DD-MON-RR'),null,'Ti�?n mặt','KH007','KM002','NV004');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD032',to_date('14-FEB-23','DD-MON-RR'),null,'Ti�?n mặt','KH018','KM002','NV004');
Insert into HOADON (MAHD,NGAYLAP,TONGTIENVAT,HINHTHUC,KHACHHANGMAKH,KHUYENMAIMAKM,NHANVIENMANV) values ('HD033',to_date('14-FEB-23','DD-MON-RR'),null,'Chuyển khoản','KH012','KM002','NV004');
REM INSERTING into KHACHHANG
SET DEFINE OFF;
Insert into KHACHHANG (MAKH,TENKH,GIOITINH,SDT,DIEMTICHLUY,HSD) values ('KH001','Nguyễn Phương Hạc','Nữ','0909234876',1,to_date('22-OCT-24','DD-MON-RR'));
Insert into KHACHHANG (MAKH,TENKH,GIOITINH,SDT,DIEMTICHLUY,HSD) values ('KH002','Ngô Dương Hà','Nam','0921873948',2,to_date('18-JAN-24','DD-MON-RR'));
Insert into KHACHHANG (MAKH,TENKH,GIOITINH,SDT,DIEMTICHLUY,HSD) values ('KH003','Nguyễn Hải Yến','Nữ','0198364782',3,to_date('22-DEC-23','DD-MON-RR'));
Insert into KHACHHANG (MAKH,TENKH,GIOITINH,SDT,DIEMTICHLUY,HSD) values ('KH004','Bùi Duy Cương','Nam','0932875439',1,to_date('15-NOV-24','DD-MON-RR'));
Insert into KHACHHANG (MAKH,TENKH,GIOITINH,SDT,DIEMTICHLUY,HSD) values ('KH005','Mai Quốc Dũng','Nam','0873291874',3,to_date('17-MAR-24','DD-MON-RR'));
Insert into KHACHHANG (MAKH,TENKH,GIOITINH,SDT,DIEMTICHLUY,HSD) values ('KH006','Lê Quang Hoàng Minh','Nam','0192837491',3,to_date('07-SEP-23','DD-MON-RR'));
Insert into KHACHHANG (MAKH,TENKH,GIOITINH,SDT,DIEMTICHLUY,HSD) values ('KH007','Lê Minh Thanh','Nam','0923849072',1,to_date('16-AUG-24','DD-MON-RR'));
Insert into KHACHHANG (MAKH,TENKH,GIOITINH,SDT,DIEMTICHLUY,HSD) values ('KH008','Nguyễn Hoài Nam','Nam','0981736284',2,to_date('13-JUN-23','DD-MON-RR'));
Insert into KHACHHANG (MAKH,TENKH,GIOITINH,SDT,DIEMTICHLUY,HSD) values ('KH009','Nguyễn Thanh Long','Nam','0923891826',2,to_date('12-MAR-23','DD-MON-RR'));
Insert into KHACHHANG (MAKH,TENKH,GIOITINH,SDT,DIEMTICHLUY,HSD) values ('KH010','Trần �?ình Toàn','Nam','0912782637',2,to_date('15-MAR-23','DD-MON-RR'));
Insert into KHACHHANG (MAKH,TENKH,GIOITINH,SDT,DIEMTICHLUY,HSD) values ('KH011','Trần Như �?','Nữ','0912782638',1,to_date('15-AUG-23','DD-MON-RR'));
Insert into KHACHHANG (MAKH,TENKH,GIOITINH,SDT,DIEMTICHLUY,HSD) values ('KH012','Trần Văn Th�?','Nam','0912935639',1,to_date('29-FEB-24','DD-MON-RR'));
Insert into KHACHHANG (MAKH,TENKH,GIOITINH,SDT,DIEMTICHLUY,HSD) values ('KH013','Vũ Văn Vinh','Nam','0912767340',1,to_date('27-MAY-23','DD-MON-RR'));
Insert into KHACHHANG (MAKH,TENKH,GIOITINH,SDT,DIEMTICHLUY,HSD) values ('KH014','Nguyễn Thị Thu Tâm','Nữ','0912782641',1,to_date('07-APR-24','DD-MON-RR'));
Insert into KHACHHANG (MAKH,TENKH,GIOITINH,SDT,DIEMTICHLUY,HSD) values ('KH015','Nguyễn Thị Bích Ngân','Nữ','0912782642',1,to_date('25-AUG-24','DD-MON-RR'));
Insert into KHACHHANG (MAKH,TENKH,GIOITINH,SDT,DIEMTICHLUY,HSD) values ('KH016','Vũ �?ức Thịnh','Nam','0912782643',1,to_date('30-NOV-23','DD-MON-RR'));
Insert into KHACHHANG (MAKH,TENKH,GIOITINH,SDT,DIEMTICHLUY,HSD) values ('KH017','�?inh Nguyễn Tr�?ng Nghĩa','Nam','0912782644',2,to_date('05-DEC-23','DD-MON-RR'));
Insert into KHACHHANG (MAKH,TENKH,GIOITINH,SDT,DIEMTICHLUY,HSD) values ('KH018','Huỳnh Thị Châu Lan','Nữ','0912782645',3,to_date('24-DEC-24','DD-MON-RR'));
Insert into KHACHHANG (MAKH,TENKH,GIOITINH,SDT,DIEMTICHLUY,HSD) values ('KH019','Phan Thị Ng�?c Mai','Nữ','0912782646',1,to_date('01-OCT-23','DD-MON-RR'));
Insert into KHACHHANG (MAKH,TENKH,GIOITINH,SDT,DIEMTICHLUY,HSD) values ('KH020','Mạnh Thiên Lý','Nữ','0912782647',1,to_date('19-MAY-24','DD-MON-RR'));
REM INSERTING into KHONGUYENLIEU
SET DEFINE OFF;
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL001','Cà phê bột',300,'Bao');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL002','�?ư�?ng trắng',150,'Bao');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL003','�?á Viên',30,'Bao');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL004','Sữa đặc',20,'Lon');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL005','Sữa tươi không đư�?ng',15,'Thùng');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL006','Bột chocolate',20,'Bao');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL007','Trà nhài',50,'Hộp');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL008','Hạt cà phê',200,'Bao');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL009','Kem Rich',20,'Hộp');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL010','Sốt  dark chocolate',20,'Chai');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL011','Siro hoa quả',30,'Chai');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL012','Mứt đào',30,'Lon');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL013','Bánh Oreo',5,'Thùng');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL014','Bánh Ritz',5,'Thùng');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL015','Mứt xoài',20,'Lon');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL016','Mứt dâu',10,'Lon');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL017','Sốt caramel',15,'Chai');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL018','Kem Base',25,'Hộp');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL019','Kem Vani',15,'Hộp');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL020','Bột cacao',15,'Bao');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL021','Bột onemix',25,'Bao');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL022','Trà sen',20,'Hộp');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL023','Trà olong',25,'Hộp');
Insert into KHONGUYENLIEU (MANL,TENNL,SOLUONG,DONVI) values ('NL024','Trà Lipton',30,'Hộp');
REM INSERTING into KHUYENMAI
SET DEFINE OFF;
Insert into KHUYENMAI (MAKM,TENKM,TILE) values ('KM001','Khuyến mãi Tết',0.2);
Insert into KHUYENMAI (MAKM,TENKM,TILE) values ('KM002','Khuyến mãi Valentine',0.1);
Insert into KHUYENMAI (MAKM,TENKM,TILE) values ('KM003','Khuyến mãi 8/3',0.1);
Insert into KHUYENMAI (MAKM,TENKM,TILE) values ('KM004','Khuyến mãi 30/4',0.1);
Insert into KHUYENMAI (MAKM,TENKM,TILE) values ('KM005','Khuyến mãi Trung Thu',0.1);
Insert into KHUYENMAI (MAKM,TENKM,TILE) values ('KM006','Khuyến mãi Black Friday',0.2);
Insert into KHUYENMAI (MAKM,TENKM,TILE) values ('KM007','Khuyến mãi Giáng Sinh',0.1);
REM INSERTING into NHANVIEN
SET DEFINE OFF;
Insert into NHANVIEN (MANV,TENNV,SDT,GIOITINH,TAIKHOAN) values ('NV001','Trần Thị Mai','0986752347','Nữ','mai01');
Insert into NHANVIEN (MANV,TENNV,SDT,GIOITINH,TAIKHOAN) values ('NV002','�?i Thanh Thư','0996282378','Nữ','thu02');
Insert into NHANVIEN (MANV,TENNV,SDT,GIOITINH,TAIKHOAN) values ('NV003','Tâm Như Nguyệt','0305812409','Nữ','nguyet03');
Insert into NHANVIEN (MANV,TENNV,SDT,GIOITINH,TAIKHOAN) values ('NV004','Nguyễn Văn An','0876879009','Nam','an04');
Insert into NHANVIEN (MANV,TENNV,SDT,GIOITINH,TAIKHOAN) values ('NV005','Hồ Ng�?c Hà','0386875637','Nữ','ha05');
Insert into NHANVIEN (MANV,TENNV,SDT,GIOITINH,TAIKHOAN) values ('NV006','Nguyễn Thị Kim Oanh','0385811400','Nữ','oanh06');
Insert into NHANVIEN (MANV,TENNV,SDT,GIOITINH,TAIKHOAN) values ('NV007','Dương Thị Mai Thi','0986752344','Nữ','thi07');
Insert into NHANVIEN (MANV,TENNV,SDT,GIOITINH,TAIKHOAN) values ('NV008','Phạm Hùng Vương','0996282378','Nam','vuong08');
Insert into NHANVIEN (MANV,TENNV,SDT,GIOITINH,TAIKHOAN) values ('NV009','Trần Thanh Huy','0674912891','Nữ','huy09');
Insert into NHANVIEN (MANV,TENNV,SDT,GIOITINH,TAIKHOAN) values ('NV010','Hồ Tuấn Dương','0986757453','Nam','duong10');
REM INSERTING into PHANLOAI
SET DEFINE OFF;
Insert into PHANLOAI (MALOAI,TENLOAI) values ('ML001','Cà phê');
Insert into PHANLOAI (MALOAI,TENLOAI) values ('ML002','Sinh tố');
Insert into PHANLOAI (MALOAI,TENLOAI) values ('ML003','Nước ép');
Insert into PHANLOAI (MALOAI,TENLOAI) values ('ML004','MilkShake');
Insert into PHANLOAI (MALOAI,TENLOAI) values ('ML005','Topping');
Insert into PHANLOAI (MALOAI,TENLOAI) values ('ML006','Kem - Sữa Chua');
REM INSERTING into PHIEUNHAP
SET DEFINE OFF;
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN001',to_date('10-OCT-23','DD-MON-RR'),'NV001');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN002',to_date('24-NOV-23','DD-MON-RR'),'NV002');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN003',to_date('28-FEB-23','DD-MON-RR'),'NV009');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN004',to_date('14-AUG-23','DD-MON-RR'),'NV003');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN005',to_date('23-NOV-23','DD-MON-RR'),'NV001');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN006',to_date('23-NOV-23','DD-MON-RR'),'NV009');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN007',to_date('22-OCT-23','DD-MON-RR'),'NV002');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN008',to_date('10-DEC-23','DD-MON-RR'),'NV002');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN009',to_date('10-DEC-23','DD-MON-RR'),'NV002');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN010',to_date('10-DEC-23','DD-MON-RR'),'NV003');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN011',to_date('10-DEC-23','DD-MON-RR'),'NV005');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN012',to_date('28-FEB-23','DD-MON-RR'),'NV005');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN013',to_date('20-JUL-23','DD-MON-RR'),'NV003');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN014',to_date('25-DEC-23','DD-MON-RR'),'NV001');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN015',to_date('26-NOV-23','DD-MON-RR'),'NV005');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN016',to_date('28-FEB-23','DD-MON-RR'),'NV003');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN017',to_date('22-SEP-23','DD-MON-RR'),'NV003');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN018',to_date('22-SEP-23','DD-MON-RR'),'NV006');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN019',to_date('28-DEC-23','DD-MON-RR'),'NV010');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN020',to_date('22-SEP-23','DD-MON-RR'),'NV001');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN021',to_date('22-SEP-23','DD-MON-RR'),'NV001');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN022',to_date('28-FEB-23','DD-MON-RR'),'NV009');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN023',to_date('23-NOV-23','DD-MON-RR'),'NV007');
Insert into PHIEUNHAP (MAPN,NGAYNHAP,NHANVIENMANV) values ('PN024',to_date('26-NOV-23','DD-MON-RR'),'NV008');
REM INSERTING into THUCDON
SET DEFINE OFF;
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD001','Cafe đen',30000,'L','01','Cà phê đen là một trong những loại thức uống quen thuộc của ngư�?i Việt. �?ược làm từ cà phê nguyên chất 100% cà phê đen mang hương vị đậm đà mạnh mẽ giúp bạn tỉnh táo và tái tạo năng lượng','ML001');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD002','Cafe đen',25000,'M','01','Cà phê đen là một trong những loại thức uống quen thuộc của ngư�?i Việt. �?ược làm từ cà phê nguyên chất 100% cà phê đen mang hương vị đậm đà mạnh mẽ giúp bạn tỉnh táo và tái tạo năng lượng','ML001');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD003','Cafe Espresso',45000,'L','01','Cà phê espresso được pha chế bằng cách dùng nước nóng nén dưới áp suất cao (khoảng 9 đến 10 bar) qua bột cà phê được xay mịn','ML001');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD004','Cafe Espresso',40000,'M','01','Cà phê espresso được pha chế bằng cách dùng nước nóng nén dưới áp suất cao (khoảng 9 đến 10 bar) qua bột cà phê được xay mịn','ML001');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD005','American cafe',50000,'L','01','Caffè Americano hay Americano (tiếng Anh: American coffee – Cà phê Mỹ) là một phong cách cà phê chuẩn bị bằng cách thêm nước nóng vào espresso - đi�?u này làm cà phê có độ đậm tương tự nhưng hương vị lại khác giống cà phê phin','ML001');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD006','American cafe',45000,'M','01','Caffè Americano hay Americano (tiếng Anh: American coffee – Cà phê Mỹ) là một phong cách cà phê chuẩn bị bằng cách thêm nước nóng vào espresso - đi�?u này làm cà phê có độ đậm tương tự nhưng hương vị lại khác giống cà phê phin','ML001');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD007','Sinh tố bơ',27000,'M','01','Bơ là một loại trái cây bổ dưỡng có lợi cho hệ tiêu hóa...  đặc biệt là cực kỳ tốt cho sự phát triển của thai nhi giúp kh�?e mạnh và thông minh','ML002');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD008','Sinh tố bơ',23000,'l','01','Bơ là một loại trái cây bổ dưỡng có lợi cho hệ tiêu hóa...  đặc biệt là cực kỳ tốt cho sự phát triển của thai nhi giúp kh�?e mạnh và thông minh','ML002');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD009','Sinh tố chuối vị Socola',31000,'M','01','Sinh tố chuối vị lạ mà ngon - uống cực kỳ tốt cho hệ tiêu hóa đặc biệt có thể dùng để giảm cân vì có chứa  chất trytophan kích thích giấc ngủ ngon và cải thiện sự suy nhược của cơ thể','ML002');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD010','Sinh tố chuối vị Socola',38000,'L','01','Sinh tố chuối vị lạ mà ngon - uống cực kỳ tốt cho hệ tiêu hóa đặc biệt có thể dùng để giảm cân vì có chứa  chất trytophan kích thích giấc ngủ ngon và cải thiện sự suy nhược của cơ thể','ML002');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD011','Sinh tố cam sữa chua',31000,'M','01','Cam và sữa chua đ�?u có chứa các loại vitamin cần thiết cho cơ thể đặc biệt với khả năng làm đẹp an toàn và hiệu quả ít tốn kém','ML002');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD012','Sinh tố chuối vị Socola',38000,'L','01','Cách làm sinh tố chuối socola với sự kết hợp độc đáo của chuối và socola thật tuyệt. Khi xay xong cho sinh tố ra ly bạn có thể thêm chút topping điểm cho ly sinh tố thêm lung linh như ngoài hàng nhé!','ML002');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD013','Sinh tố chuối vị Socola',31000,'M','01','Cách làm sinh tố chuối socola với sự kết hợp độc đáo của chuối và socola thật tuyệt. Khi xay xong cho sinh tố ra ly bạn có thể thêm chút topping điểm cho ly sinh tố thêm lung linh như ngoài hàng nhé!','ML002');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD014','Nước ép cam',22000,'L','01','Cam là loại trái cay giàu vitamin và khoáng chất đặc biệt phù hợp để bổ sung sức đ�? kháng cho cơ thể khi bị ốm','ML003');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD015','Nước ép cam',18000,'M','01','Cam là loại trái cay giàu vitamin và khoáng chất đặc biệt phù hợp để bổ sung sức đ�? kháng cho cơ thể khi bị ốm','ML003');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD017','Nước ép cà rốt',20000,'L','01','Nước ép cà rốt cũng hỗ trợ hạ đư�?ng huyết có tác dụng ngăn ngừa ung thư nhuận tràng và đi�?u trị táo bón hiệu quả','ML003');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD018','Nước ép cà rốt',18000,'M','01','Cam và sữa chua đ�?u có chứa các loại vitamin cần thiết cho cơ thể đặc biệt với khả năng làm đẹp an toàn và hiệu quả ít tốn kém','ML003');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD019','Nước ép táo',24000,'L','01','Nước ép táo cũng là một trong những loại nước ép giúp giảm cân hiệu quả. Nước táo ép chứa nhi�?u vitamin A- C- B1- B2- K- giúp chống oxy hóa và có lợi cho hệ miễn dịch','ML003');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD020','Nước ép táo',20000,'M','01','Nước ép táo cũng là một trong những loại nước ép giúp giảm cân hiệu quả. Nước táo ép chứa nhi�?u vitamin A- C- B1- B2- K- giúp chống oxy hóa và có lợi cho hệ miễn dịch','ML003');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD021','Milkshake bánh quy và kem',31000,'M','01','Sữa - Kem vani - Bánh oreo','ML004');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD022','Milkshake bánh quy và kem',38000,'L','01','Sữa - Kem vani - Bánh oreo','ML004');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD023','Milkshake chocolate đen và dừa',40000,'L','01','Chocolate đắng - Nước cốt dừa - Kem chocolate - Cacao - Dừa bào sợi','ML004');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD024','Milkshake chocolate đen và dừa',38000,'M','01','Chocolate đắng - Nước cốt dừa - Kem chocolate - Cacao - Dừa bào sợi','ML004');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD025','Matcha Milkshake',35000,'M','01','Sữa tươi - nước nóng -  Matcha - đư�?ng - Wiping cream','ML004');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD026','Matcha Milkshake',40000,'L','01','Sữa tươi - nước nóng -  Matcha - đư�?ng - Wiping cream','ML004');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD027','Trân châu đen',5000,'M','01','Vị dai ngon dẻo mịn đặc trưng của bột nếp đã khiến cho trân châu đen rất thích hợp được dùng kèm khi thưởng thức trà sữa','ML005');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD028','Trân châu trắng',5000,'M','01','Chỉ với các nguyên liệu đơn giản là bạn đã có ngay cho mình những viên trân châu trắng giòn dai trong suốt để thưởng thức cùng trà sữa.','ML005');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD029','Thạch trái cây',7000,'M','01','Thạch trái cây có vị ng�?t thanh thơm ngon nên kết hợp với trà sữa béo thơm vô cùng hợp vị và làm tăng thêm hương vị của trà sữa lên nhi�?u lần','ML005');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD030','Thạch cà phê',8000,'M','01','Thạch cà phê thơm ngon với màu sắc đặc trưng của cà phê khi ăn ta sẽ cảm nhận được lớp thạch giòn dai sựt sựt hòa quyện cùng vị béo của phô mai và chút hương thơm thoang thoảng nồng đậm của cà phê','ML005');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD031','Sương sáo',10000,'M','01','Sương sáo ng�?t thơm m�?m mịn hòa cùng trà sữa beo béo. Cho thêm chút đá viên vào nữa là siêu ngon!','ML005');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD032','Kem Gelato',30000,'M','01','Kem Gelato cũng là một lựa chon cho ngày hè nóng bức bởi cảm giác nhẹ nhàng thanh mát chứ không h�? ngậy một chút nào. Cùng thưởng thức món kem này ngay nhé','ML006');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD033','Kem phô mai',35000,'M','01','Món kem phô mai ở Hokkaido Cheese Tart lại là “cực phẩm�? đấy! Ở đây sẽ có cho bạn kem phô mai thư�?ng và kem phô mai trân châu đấy nhé','ML006');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD034','Sữa chua túi',5000,'M','01','Mỗi khi ăn nó sẽ giúp bạn gợi nhớ v�? một th�?i tuổi thơ của mình vì đây là một trong những món ăn vặt đỉnh cao th�?i 8x 9x đấy!','ML006');
Insert into THUCDON (MAMON,TENMON,GIA,KICHCO,TRANGTHAI,MOTA,PHANLOAIMALOAI) values ('TD035','Sữa chua nếp cẩm',15000,'M','01','Sữa chua nếp cẩm trong tay. Những hạt nếp cẩm thơm bùi ăn cùng sữa chua dẻo trắng mịn lại còn được thêm nước cốt dừa trân châu nữa!','ML006');
REM INSERTING into XUATNGUYENLIEU
SET DEFINE OFF;
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX001',to_date('20-APR-23','DD-MON-RR'),'NV001');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX002',to_date('28-JUN-23','DD-MON-RR'),'NV003');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX003',to_date('10-DEC-23','DD-MON-RR'),'NV004');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX004',to_date('22-SEP-23','DD-MON-RR'),'NV009');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX005',to_date('11-FEB-23','DD-MON-RR'),'NV010');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX006',to_date('12-JUN-23','DD-MON-RR'),'NV008');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX007',to_date('16-AUG-23','DD-MON-RR'),'NV001');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX008',to_date('17-OCT-23','DD-MON-RR'),'NV009');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX009',to_date('03-MAR-23','DD-MON-RR'),'NV002');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX010',to_date('17-OCT-23','DD-MON-RR'),'NV004');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX011',to_date('21-JUL-23','DD-MON-RR'),'NV004');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX012',to_date('20-APR-23','DD-MON-RR'),'NV009');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX013',to_date('20-APR-23','DD-MON-RR'),'NV009');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX014',to_date('20-APR-23','DD-MON-RR'),'NV002');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX015',to_date('12-JUN-23','DD-MON-RR'),'NV008');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX016',to_date('21-JUL-23','DD-MON-RR'),'NV007');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX017',to_date('05-JAN-23','DD-MON-RR'),'NV007');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX018',to_date('23-MAY-23','DD-MON-RR'),'NV005');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX019',to_date('26-JUN-23','DD-MON-RR'),'NV006');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX020',to_date('21-JUL-23','DD-MON-RR'),'NV010');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX021',to_date('21-JUL-23','DD-MON-RR'),'NV001');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX022',to_date('23-MAY-23','DD-MON-RR'),'NV006');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX023',to_date('21-JUL-23','DD-MON-RR'),'NV010');
Insert into XUATNGUYENLIEU (MAXUAT,NGAYXUAT,NHANVIENMANV) values ('MX024',to_date('21-JUL-23','DD-MON-RR'),'NV008');
--------------------------------------------------------
--  DDL for Index SYS_C0010013
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0010013" ON "CHITIETHOADON" ("HOADONMAHD", "THUCDONMAMON") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010028
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0010028" ON "CHITIETPHIEUNHAP" ("NGUYENLIEUMANL", "PHIEUNHAPMAPN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010041
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0010041" ON "CHITIETXUAT" ("KHONGUYENLIEUMANL", "XUATNGUYENLIEUMAXUAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010004
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0010004" ON "HOADON" ("MAHD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010017
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0010017" ON "KHACHHANG" ("MAKH") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
--------------------------------------------------------
--  DDL for Index SYS_C0010025
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0010025" ON "KHONGUYENLIEU" ("MANL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010015
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0010015" ON "KHUYENMAI" ("MAKM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010038
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0010038" ON "NHANVIEN" ("MANV") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010009
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0010009" ON "PHANLOAI" ("MALOAI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010021
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0010021" ON "PHIEUNHAP" ("MAPN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010007
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0010007" ON "THUCDON" ("MAMON") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010034
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C0010034" ON "XUATNGUYENLIEU" ("MAXUAT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CHITIETHOADON
--------------------------------------------------------

  ALTER TABLE "CHITIETHOADON" ADD PRIMARY KEY ("HOADONMAHD", "THUCDONMAMON")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHITIETHOADON" MODIFY ("THUCDONMAMON" NOT NULL ENABLE);
  ALTER TABLE "CHITIETHOADON" MODIFY ("HOADONMAHD" NOT NULL ENABLE);
  ALTER TABLE "CHITIETHOADON" MODIFY ("SOLUONG" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHITIETPHIEUNHAP
--------------------------------------------------------

  ALTER TABLE "CHITIETPHIEUNHAP" ADD PRIMARY KEY ("NGUYENLIEUMANL", "PHIEUNHAPMAPN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHITIETPHIEUNHAP" MODIFY ("PHIEUNHAPMAPN" NOT NULL ENABLE);
  ALTER TABLE "CHITIETPHIEUNHAP" MODIFY ("NGUYENLIEUMANL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHITIETXUAT
--------------------------------------------------------

  ALTER TABLE "CHITIETXUAT" ADD PRIMARY KEY ("KHONGUYENLIEUMANL", "XUATNGUYENLIEUMAXUAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "CHITIETXUAT" MODIFY ("XUATNGUYENLIEUMAXUAT" NOT NULL ENABLE);
  ALTER TABLE "CHITIETXUAT" MODIFY ("KHONGUYENLIEUMANL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HOADON
--------------------------------------------------------

  ALTER TABLE "HOADON" ADD PRIMARY KEY ("MAHD")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HOADON" MODIFY ("NHANVIENMANV" NOT NULL ENABLE);
  ALTER TABLE "HOADON" MODIFY ("KHACHHANGMAKH" NOT NULL ENABLE);
  ALTER TABLE "HOADON" MODIFY ("NGAYLAP" NOT NULL ENABLE);
  ALTER TABLE "HOADON" MODIFY ("MAHD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KHACHHANG
--------------------------------------------------------

  ALTER TABLE "KHACHHANG" ADD PRIMARY KEY ("MAKH")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHACHHANG" MODIFY ("MAKH" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KHONGUYENLIEU
--------------------------------------------------------

  ALTER TABLE "KHONGUYENLIEU" ADD PRIMARY KEY ("MANL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHONGUYENLIEU" MODIFY ("DONVI" NOT NULL ENABLE);
  ALTER TABLE "KHONGUYENLIEU" MODIFY ("SOLUONG" NOT NULL ENABLE);
  ALTER TABLE "KHONGUYENLIEU" MODIFY ("MANL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KHUYENMAI
--------------------------------------------------------

  ALTER TABLE "KHUYENMAI" ADD PRIMARY KEY ("MAKM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "KHUYENMAI" MODIFY ("MAKM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table NHANVIEN
--------------------------------------------------------

  ALTER TABLE "NHANVIEN" ADD PRIMARY KEY ("MANV")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "NHANVIEN" MODIFY ("MANV" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PHANLOAI
--------------------------------------------------------

  ALTER TABLE "PHANLOAI" ADD PRIMARY KEY ("MALOAI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PHANLOAI" MODIFY ("MALOAI" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PHIEUNHAP
--------------------------------------------------------

  ALTER TABLE "PHIEUNHAP" ADD PRIMARY KEY ("MAPN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "PHIEUNHAP" MODIFY ("NHANVIENMANV" NOT NULL ENABLE);
  ALTER TABLE "PHIEUNHAP" MODIFY ("NGAYNHAP" NOT NULL ENABLE);
  ALTER TABLE "PHIEUNHAP" MODIFY ("MAPN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table THUCDON
--------------------------------------------------------

  ALTER TABLE "THUCDON" ADD PRIMARY KEY ("MAMON")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "THUCDON" MODIFY ("PHANLOAIMALOAI" NOT NULL ENABLE);
  ALTER TABLE "THUCDON" MODIFY ("MAMON" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table XUATNGUYENLIEU
--------------------------------------------------------

  ALTER TABLE "XUATNGUYENLIEU" ADD PRIMARY KEY ("MAXUAT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "XUATNGUYENLIEU" MODIFY ("NHANVIENMANV" NOT NULL ENABLE);
  ALTER TABLE "XUATNGUYENLIEU" MODIFY ("MAXUAT" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CHITIETHOADON
--------------------------------------------------------

  ALTER TABLE "CHITIETHOADON" ADD CONSTRAINT "CÓ" FOREIGN KEY ("HOADONMAHD")
	  REFERENCES "HOADON" ("MAHD") ENABLE;
  ALTER TABLE "CHITIETHOADON" ADD CONSTRAINT "TRONG" FOREIGN KEY ("THUCDONMAMON")
	  REFERENCES "THUCDON" ("MAMON") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHITIETPHIEUNHAP
--------------------------------------------------------

  ALTER TABLE "CHITIETPHIEUNHAP" ADD CONSTRAINT "Bao gồm" FOREIGN KEY ("PHIEUNHAPMAPN")
	  REFERENCES "PHIEUNHAP" ("MAPN") ENABLE;
  ALTER TABLE "CHITIETPHIEUNHAP" ADD CONSTRAINT "NHẬP" FOREIGN KEY ("NGUYENLIEUMANL")
	  REFERENCES "KHONGUYENLIEU" ("MANL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CHITIETXUAT
--------------------------------------------------------

  ALTER TABLE "CHITIETXUAT" ADD CONSTRAINT "VOI" FOREIGN KEY ("XUATNGUYENLIEUMAXUAT")
	  REFERENCES "XUATNGUYENLIEU" ("MAXUAT") ENABLE;
  ALTER TABLE "CHITIETXUAT" ADD CONSTRAINT "XUẤT" FOREIGN KEY ("KHONGUYENLIEUMANL")
	  REFERENCES "KHONGUYENLIEU" ("MANL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HOADON
--------------------------------------------------------

  ALTER TABLE "HOADON" ADD CONSTRAINT "In" FOREIGN KEY ("NHANVIENMANV")
	  REFERENCES "NHANVIEN" ("MANV") ENABLE;
  ALTER TABLE "HOADON" ADD CONSTRAINT "Thanh Toán" FOREIGN KEY ("KHACHHANGMAKH")
	  REFERENCES "KHACHHANG" ("MAKH") ENABLE;
  ALTER TABLE "HOADON" ADD CONSTRAINT "�?p dụng" FOREIGN KEY ("KHUYENMAIMAKM")
	  REFERENCES "KHUYENMAI" ("MAKM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PHIEUNHAP
--------------------------------------------------------

  ALTER TABLE "PHIEUNHAP" ADD CONSTRAINT "Thực Hiện" FOREIGN KEY ("NHANVIENMANV")
	  REFERENCES "NHANVIEN" ("MANV") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table THUCDON
--------------------------------------------------------

  ALTER TABLE "THUCDON" ADD CONSTRAINT "THUỘC" FOREIGN KEY ("PHANLOAIMALOAI")
	  REFERENCES "PHANLOAI" ("MALOAI") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table XUATNGUYENLIEU
--------------------------------------------------------

  ALTER TABLE "XUATNGUYENLIEU" ADD CONSTRAINT "Yêu Cầu" FOREIGN KEY ("NHANVIENMANV")
	  REFERENCES "NHANVIEN" ("MANV") ENABLE;


--tạo profile
Create Profile KhachHang LIMIT
                                            FAILED_LOGIN_ATTEMPTS 3
                                            PASSWORD_LIFE_TIME 90
                                            IDLE_TIME 5
                                            SESSIONS_PER_USER 2
                                            PASSWORD_REUSE_TIME  30
                                            PASSWORD_REUSE_MAX  3
                                            PASSWORD_GRACE_TIME 5
                                            PASSWORD_LOCK_TIME  30
                                        
--tạo use vs profile
CREATE USER Kun1 IDENTIFIED BY kun123 PROFILE KhachHang;
--cấp quy�?n
GRANT CREATE SESSION TO Nghiakun ;
GRANT CREATE TABLE TO Nghiakun;
GRANT UNLIMITED TABLESPACE TO Nghiakun;
--
GRANT CONNECT TO nguoidung1;


commit work;
ALTER USER nguoidung1 IDENTIFIED BY abc1234;
---lệnh check user hết hạn 
SELECT USERNAME, ACCOUNT_STATUS FROM DBA_USERS WHERE USERNAME = 'nguoidung1';

    Drop user kun1 cascade
    CREATE USER Kun1 IDENTIFIED BY kun123
---
SELECT 
  * 
FROM 
    dba_profiles
WHERE 
    PROFILE = 'DEFAULT'
